format = """$username @ $localip $os in $directory $all"""

command_timeout = 1500

[os]
disabled=false
format = '[$symbol](green)'

[os.symbols]
Alpine = "🏔️"
Android = "🤖"
Arch = "🎗️"
CentOS = "💠"
Debian = "🌀"
Fedora = "🎩"
FreeBSD = "😈"
Gentoo = "🗜️"
Kali = "🐉"
Linux = "🐧"
Macos = "🍎"
Mint = "🌿"
NetBSD = "🚩"
NixOS = "❄️"
OpenBSD = "🐡"
openSUSE = "🦎 "
Raspbian = "🍓"
Redhat = "🎩"
RedHatEnterprise = "🎩"
Ubuntu = "🎯"
Windows = "🪟"

[character]
success_symbol = "[➜](bold purple)" 
error_symbol = "[✖](bold red) "

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 20
style = "bold red"
discharging_symbol = "⚡"
charging_symbol = "🔌"
[[battery.display]]
threshold = 99
style = "yellow"
discharging_symbol = "⚡"
charging_symbol = "🔌"
[[battery.display]]
threshold = 100
discharging_symbol = "🔋"
charging_symbol = "🔋"

[c]
format = "via [$name $version]($style)"
[sudo]
style = "bold green"
symbol = "👩‍💻 "
disabled = false

[git_status]
conflicted = "⚔️ "
ahead = "🏎️ 💨 ×${count}"
behind = "🐢 ×${count}"
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
untracked = "🛤️  ×${count}"
stashed = "📦 "
modified = "📝 ×${count}"
staged = "🗃️  ×${count}"
renamed = "📛 ×${count}"
deleted = "🗑️  ×${count}"
style = "bright-white"
format = "$all_status$ahead_behind"


[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = false

[username]
format = "[$user]($style)"
style_user = "bold blue"
show_always = true

[custom.cpu]
command = '''
lscpu | awk -F: '/Model name/ {gsub(/^ +/, "", $2); print $2}' \
| grep -oE '(i[3579]-[A-Za-z0-9]+|Ryzen [0-9]+ [0-9A-Za-z]+)' \
| head -n1
'''
when = "true"
format = "CPU: [$output]($style) "
style = "bold cyan"

[custom.cpu_utilization]
command = "top -bn1 | grep 'Cpu(s)' | sed 's/.*, \\([0-9.]*\\)%* id.*/\\1/' | awk '{print 100 - $1\"%\"}'"
when = "true"
format = " [$output]($style) "
style = "bold green"

[localip]
ssh_only = false
format = '[$localipv4](#FFC0CB)'
disabled = false

[directory]
format = "[$path]($style)"
