format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_commit\
$all\
$fill\
[](blue)\
[ ${custom.cpu} ${custom.cpu_utilization} ](bg:blue fg:#bac2de)\
[ ${custom.memory} ](bg:cyan fg:#bac2de)\
[ ${localip} ](bg:green fg:#bac2de)\
[](green)\
$line_break\
[╰─](bold green_bright)\
$character\
$time\
$cmd_duration\
$sudo\
$status
"""

[fill]
symbol = ' '

[sudo]
style = "bold green"
symbol = "👩 "
disabled = false

[directory]
read_only = " 󰌾"
style = "fg:blue"
read_only_style = "fg:bright-red"
truncation_length = 3
truncation_symbol = "…/"
format = "[ $path]($style)[$read_only]($read_only_style) "

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 20
style = "bold red"
discharging_symbol = "⚡"
charging_symbol = "🔌"

[[battery.display]]
threshold = 99
style = "yellow"
discharging_symbol = "⚡"
charging_symbol = "🔌"

[[battery.display]]
threshold = 100
discharging_symbol = "🔋"
charging_symbol = "🔋"

[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = false

[cmd_duration]
disabled = false
min_time = 2000
format = "[$duration]($style) "
style = "bold fg:yellow"

[aws]
disabled = true
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "
format = "[$name $version]($style)"

[cmake]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = "  "

[git_status]
conflicted = "⚔️ "
ahead = "🏎️ 💨 ×${count}"
behind = "🐢 ×${count}"
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
untracked = "🛤️  ×${count}"
stashed = "📦 "
modified = "📝 ×${count}"
staged = "🗃️  ×${count}"
renamed = "📛 ×${count}"
deleted = "🗑️  ×${count}"
style = "bright-white"
format = "$all_status$ahead_behind "

[golang]
symbol = " "

[guix_shell]
disabled = true
symbol = " "

[haskell]
disabled = true
symbol = " "

[haxe]
disabled = true
symbol = " "

[hg_branch]
disabled = true
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
disabled = true
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
disabled = true
symbol = "󰔷 "

[nim]
disabled = true
symbol = "󰆥 "

[nix_shell]
disabled = true
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[package]
disabled = true
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
disabled = true
symbol = " "

[python]
symbol = ""
format = " [$symbol $version]($style) "

[rust]
symbol = "󱘗 "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "


# --- OS Configuration
[os]
disabled = false
format = "[$symbol ]($style)"
style = "fg:purple"


[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

# --- PC Stats
[custom.cpu]
command = '''
lscpu | awk -F: '/Model name/ {gsub(/^ +/, "", $2); print $2}' \
| grep -oE '(i[3579]-[A-Za-z0-9]+|Ryzen [0-9]+ [0-9A-Za-z]+)' \
| head -n1
'''
when = "true"
format = " $output"

[custom.cpu_utilization]
command = "top -bn1 | grep 'Cpu(s)' | sed 's/.*, \\([0-9.]*\\)%* id.*/\\1/' | awk '{print 100 - $1\"%\"}'"
when = "true"
format = "$output"

[custom.memory]
command = """
used=$(free -m | awk '/^Mem:/ {print $3}')
total=$(free -m | awk '/^Mem:/ {print $2}')

if [ $total -lt 1024 ]; then
  echo "$used/$total MiB"
else
  printf "%.2f/%.1f GiB\n" "$(echo "$used/1024" | bc -l)" "$(echo "$total/1024" | bc -l)"
fi
"""
when = true
format = "🧠 $output"

[localip]
ssh_only = false
format = '$localipv4'
disabled = false
